### ISSUE TITLE
Extra editor actions

### ISSUE THREAD

**Issue by Lenbok** [MulgaSoft/intellemacs#1]
Hi, glad to see emacs+ on IDEA! (I used to use emacs+ back when I used eclipse).

I have a small IDEA plugin that has a handful of extra editor actions that I missed from emacs. It looks like emacs+ already has most of them, but there are a couple extra that I would happily contribute here as a pull-request.

**Comment by mfeber** [comment]
Hi, hope you are finding it useful.  Haven't seen much response from users so far...
As I'm still working my way through the layers of IntelliJ, I haven't released the sources (or even reached a non-beta version of the plugin).  However, I'd be interested in finding out which actions you wish to see moved over from the Eclipse version (and which you've implemented that are not currently in the IntelliJ version).  I'm starting in on sexps now.  I won't be around much this week so I may not get back to you immediately.  Thx, Mark

**Comment by Lenbok** [comment]
Hi Mark,

I just discovered your intellij plugin yesterday, so haven't had much of a chance to settle in to it yet, just thought I'd initially see what it was missing that I use on a regular basis. I already like the improvements to search and replace!

The remaining ones I have implemented that aren't already covered are:
- back-to-indentation (I use C-a for move-caret-to-line-start, and M-m for back-to-indentation, same as stock emacs, default intellij has a "smart" C-a binding that toggles between the two positions, but I don't like it)
- delete-indentation (I use this often in emacs)

I see there is also this emacs plugin: https://plugins.jetbrains.com/plugin/7163 (I'm sure neither yours nor this one existed when I switched from eclipse a few years ago). Maybe worth joining forces to have a superset plugin?

**Comment by mfeber** [comment]
Expect to see back-to-indentation and delete-indentation in the next release.  BTW, I assume you know that unchecking **_Preferences -> General -> Editor -> Smart Keys -> Home_** will give you your desired behavior on C-a.

**Comment by Lenbok** [comment]
Yes exactly, that's what I use for the C-a behaviour. Looking forward to the update.

**Comment by mfeber** [comment]
version 0.3.200
