### ISSUE TITLE
Strange binding for expand selection

### ISSUE THREAD

**Issue by matklad** [MulgaSoft/intellemacs#3]
With `Emacs+` keymap, settings say that `Exmapd selection` is bound to `alt+at`.

However when I do `M-@` nothing happens. 

If I manually reassign the keybinding, settings page says that it is now `alt+shift+2` and it does work.

**Comment by mfeber** [comment]
An oversight.  Will be fixed in the next release.  Thx

**Comment by mfeber** [comment]
version 0.3.200
