### ISSUE TITLE
Can't navigate recent files list after entering text

### ISSUE THREAD

**Issue by ryankask** [MulgaSoft/intellemacs#4]
When you open the switcher and start entering some text, the file list is filtered based on matching buffer names.

Once this happens, however, you can't scroll using C-n and C-p.

By the way, thanks for this amazing project. It's great that something like ido mode is almost there!

**Comment by mfeber** [comment]
Yes.  That is very annoying, but IntelliJ has wrapped and buried the key bindings so deeply there, that there is no clean way to get at them (the arrow keys will still work, however).  If it becomes sufficiently annoying one may try to color outside the lines to resolve it...

**Comment by ryankask** [comment]
Ah, that's a shame. Still, it's much better than the current switcher. I've
filed quite a few bugs in YouTrack having to do with it. Someone pointed
out this plugin in a comment there (
https://youtrack.jetbrains.com/issue/IDEA-145321).

I'm actually inspired to see if I can implement something like ido
(vertical) mode. It's what I miss most from emacs.

**Comment by ryankask** [comment]
This seems to be fixed in Intellij IDEA 15.  (also, you can now use C-n and C-p in the default switcher)

Are you able to verify this?

**Comment by mfeber** [comment]
So far, it appears to behave correctly in 15.  However, the Emacs+
enhancements to search are tragically broken (IntelliJ did a second round
of refactoring there to which I am currently adapting).
