### ISSUE TITLE
Add tw-toggle action

### ISSUE THREAD

**Issue by matklad** [MulgaSoft/intellemacs#6]
To effectively navigate tree menues (like Project View) it is neccessary to expand and collaps tree nodes with a shortcut. IDEA allowes to set _separate_ keybindings for this two actions, but does not allow to create a shortcut for a unified toggle action. 

In my opinion it would be nice to have such a toggle action, boud to TAB (like in org-mode or maggit).

**Comment by mfeber** [comment]
By default (afaik), the ENTER key already fulfills that function in IntelliJ.  When positioned on a expandable tree node, ENTER will either expand or collapse (and when positioned on a leaf node, C-ENTER will open the element).
